#!/usr/bin/env bash

# A very simple, POSIX, dependency-free atomic lock using mkdir, with
# protection against crashed processes causing deadlocks. A lot easier to
# reason about and with fewer footguns than flock with FD inheritance and
# unintuitive deadlocks.
#
# For the lock to be held, two conditions must be met:
#
# 1. lock_dir must exist;
# 2. lock_meta_file must contain a running pid with the same starttime stored
#    (to prevent against deadlock if a process crashes in a way which does not
#    release the lock).
#
# If either of these conditions is not met (and lock_meta_file was parsed
# successfully), a new process may get the lock. This consists of:
#
# 1. Deleting lock_meta_file -- if this fails, we are racing and must fail;
# 2. Deleting the temporary lock_dir;
# 3. Doing mkdir(lock_dir) -- if this fails, we are racing and must fail;
# 4. Writing our own pid and starttime as the name of lock_meta_file.
#
# If lock_meta_file is not parsable, then we play it safe and fail closed, on
# the basis that the process simply hasn't written the total data yet.

IFS=" "

name=lock_test
lock_dir=/tmp/$name.lock

get_meta() {
    local stat partial_stat
    local pid="${1?missing pid}"

    [[ -d /proc/$pid ]] || return
    read -r stat < "/proc/$pid/stat"

    # comm may contain the field delimiter, so filter to after it.
    read -ra partial_stat <<< "${stat##*) }"

    # We're at field 3, and need to get field 22 (starttime).
    printf '%s %s\n' "$pid" "${partial_stat[19]}"
}

cleanup_stale_lock() {
    local pid starttime files lock_meta_file

    if ! [[ -d $lock_dir ]]; then
        # Ostensibly already unlocked, will be validated by atomic mkdir later
        return 0
    fi

    files=( "$lock_dir"/* )
    (( ${#files[@]} == 1 )) || return
    lock_meta_file=${files[0]}
    raw_meta=${lock_meta_file##*/}
    read -r pid starttime <<< "$raw_meta" || return

    if ! [[ $pid ]] || ! [[ $starttime ]]; then
        # Corruption
        return 1
    fi

    if [[ "$(get_meta "$pid")" != "$raw_meta" ]]; then
        # Stale lock file, this process is gone
        unlock "$lock_meta_file"
    fi
}

unlock() {
    local lock_meta_file="$1"

    # If this fails we are losing the race against another unlock and must
    # stop.
    rm -- "$lock_meta_file" || return
    rmdir "$lock_dir"
}

lock() {
    local lock_meta_file

    # We don't look at cleanup_stale_lock's exit, because `mkdir` is always the
    # authoritative indicator of successful or unsuccessful locking. This is
    # just best-effort.
    cleanup_stale_lock

    mkdir -- "$lock_dir" || return
    lock_meta_file="$lock_dir/$(get_meta "$$")"
    : > "$lock_meta_file" || return

    printf '%s\n' "$lock_meta_file"
}

example() {
    set -x

    LOCK_META_FILE=$(lock) || exit
    trap 'unlock "$LOCK_META_FILE"' EXIT

    # Actual workload.
    sleep 10
}

example
